--
----[[
--    lua 脚本, 用于秒杀服务中 保证 查询库存和扣除库存 原子性 操作
----]]
---- redis连接
----const redisClient
--
--local user_id  = KEYS[1]
--local goods_id = KEYS[2]
--redis.setnx user_id 0
--local num = redis.call( 'incr', user_id )  // 访问次数加一
--if  (tonumber(num) >5)  then
--    redis.call('expire', user_id, expire_time)  //设置过期时间
--    return 3
--end
--local item_stock = "miaosha:"..item_id..":stock" -- 秒杀商品库存key
--local user_exists = "miaosha:"..item_id..":users" -- 成功秒杀商品的用户集合key
--local user_num = redis.call( 'sismember', user_exists, user_id ) --判断user_id是否存在
--if  tonumber (user_num, 10) == 1  then
--    return 2
--end
--local left_items_count = redis.call( 'get', item_stock )
--if tonumber( left_goods_count, 10 ) <= 0  then
--    return 0
--end
--else
--    redis.call( 'decr', item_stock )
--    redis.call( 'sadd', user_exists, user_id )
--end
--return 1
